name: CICD Pipeline

on:
  push:
    branches: 
    - main
    - dev
    - feature/*

  pull_request:
    branches:
     - main
     - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run a script
        run: echo "CICD pipeline executed"